/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhirmpf;

import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import jaco.mp3.player.MP3Player;
import java.awt.Desktop;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/**
 *
 * @author RICHIE
 */
public class AplikasiFinalMPF extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiFinalMPF
     */
    public AplikasiFinalMPF() {
        initComponents();
    }
    public static final String SONG = "D:\\my music\\JKT48 - Sakura Kita Makan Bersama.mp3";
        MP3Player mp3player = new MP3Player(new File(SONG));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menukiri = new javax.swing.JPanel();
        tentangkami = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        materiit = new javax.swing.JButton();
        kalkulator = new javax.swing.JButton();
        animasi = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        menukanan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        resize = new javax.swing.JButton();
        audiobawaan = new javax.swing.JButton();
        ubahhorizontal = new javax.swing.JButton();
        ubahvertikal = new javax.swing.JButton();
        audioplusmp4 = new javax.swing.JButton();
        putarvideo = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        berhenti = new javax.swing.JButton();
        Grayscalebtn = new javax.swing.JButton();
        menutengahatas = new javax.swing.JPanel();
        isitentangkami = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isiberanda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        menutengahbawah = new javax.swing.JPanel();
        display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);

        background.setBackground(new java.awt.Color(0, 204, 51));
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setOpaque(false);
        background.setPreferredSize(new java.awt.Dimension(789, 531));

        menukiri.setBackground(new java.awt.Color(52, 152, 219));
        menukiri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        tentangkami.setBackground(new java.awt.Color(255, 255, 0));
        tentangkami.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tentangkami.setForeground(new java.awt.Color(0, 0, 255));
        tentangkami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/question.png"))); // NOI18N
        tentangkami.setText("Tentang Kami");
        tentangkami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangkamiActionPerformed(evt);
            }
        });

        beranda.setBackground(new java.awt.Color(255, 255, 0));
        beranda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(0, 0, 255));
        beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/home-run.png"))); // NOI18N
        beranda.setText("Beranda");
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/features.png"))); // NOI18N
        jLabel2.setText("Fitur di Aplikasi Ini : ");

        materiit.setBackground(new java.awt.Color(204, 255, 255));
        materiit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        materiit.setForeground(new java.awt.Color(255, 0, 51));
        materiit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/code.png"))); // NOI18N
        materiit.setText("Materi IT");
        materiit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiitActionPerformed(evt);
            }
        });

        kalkulator.setBackground(new java.awt.Color(204, 255, 255));
        kalkulator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kalkulator.setForeground(new java.awt.Color(255, 0, 51));
        kalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/calculator.png"))); // NOI18N
        kalkulator.setText("Kalkulator");
        kalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalkulatorActionPerformed(evt);
            }
        });

        animasi.setBackground(new java.awt.Color(204, 255, 255));
        animasi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        animasi.setForeground(new java.awt.Color(255, 0, 0));
        animasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/animation.png"))); // NOI18N
        animasi.setText("Animasi");
        animasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animasiActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(204, 255, 255));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 0));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/exit.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        stop.setBackground(new java.awt.Color(204, 255, 255));
        stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 0, 0));
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/stop.png"))); // NOI18N
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menukiriLayout = new javax.swing.GroupLayout(menukiri);
        menukiri.setLayout(menukiriLayout);
        menukiriLayout.setHorizontalGroup(
            menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menukiriLayout.createSequentialGroup()
                .addGroup(menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menukiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tentangkami, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menukiriLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(materiit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(kalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animasi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menukiriLayout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        menukiriLayout.setVerticalGroup(
            menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menukiriLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(tentangkami, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(materiit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(animasi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(menukiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menukiriLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        menukanan.setBackground(new java.awt.Color(52, 152, 219));
        menukanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/plugin.png"))); // NOI18N
        jLabel4.setText("Fitur Tambahan : ");

        resize.setBackground(new java.awt.Color(153, 255, 204));
        resize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/expand.png"))); // NOI18N
        resize.setText("Resize Gambar");
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });

        audiobawaan.setBackground(new java.awt.Color(255, 204, 204));
        audiobawaan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        audiobawaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/enable-sound.png"))); // NOI18N
        audiobawaan.setText("Putar Audio");
        audiobawaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiobawaanActionPerformed(evt);
            }
        });

        ubahhorizontal.setBackground(new java.awt.Color(153, 255, 204));
        ubahhorizontal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubahhorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/arrow.png"))); // NOI18N
        ubahhorizontal.setText("Ubah Horizontal");
        ubahhorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahhorizontalActionPerformed(evt);
            }
        });

        ubahvertikal.setBackground(new java.awt.Color(153, 255, 204));
        ubahvertikal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubahvertikal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/sort.png"))); // NOI18N
        ubahvertikal.setText("Ubah Vertikal");
        ubahvertikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahvertikalActionPerformed(evt);
            }
        });

        audioplusmp4.setBackground(new java.awt.Color(255, 204, 204));
        audioplusmp4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        audioplusmp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/mp4.png"))); // NOI18N
        audioplusmp4.setText("Audio Dengan Mp4");
        audioplusmp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioplusmp4ActionPerformed(evt);
            }
        });

        putarvideo.setBackground(new java.awt.Color(255, 204, 204));
        putarvideo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        putarvideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/play-button.png"))); // NOI18N
        putarvideo.setText("Putar Video");
        putarvideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putarvideoActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(255, 204, 204));
        pause.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/pause.png"))); // NOI18N
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        berhenti.setBackground(new java.awt.Color(255, 204, 204));
        berhenti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        berhenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/stop.png"))); // NOI18N
        berhenti.setText("Stop");
        berhenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berhentiActionPerformed(evt);
            }
        });

        Grayscalebtn.setBackground(new java.awt.Color(153, 255, 204));
        Grayscalebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Grayscalebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/black-and-white.png"))); // NOI18N
        Grayscalebtn.setText("Gambar Grayscale");
        Grayscalebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscalebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menukananLayout = new javax.swing.GroupLayout(menukanan);
        menukanan.setLayout(menukananLayout);
        menukananLayout.setHorizontalGroup(
            menukananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menukananLayout.createSequentialGroup()
                .addGroup(menukananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menukananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menukananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(audiobawaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubahhorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubahvertikal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(audioplusmp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(putarvideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(berhenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menukananLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menukananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Grayscalebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menukananLayout.setVerticalGroup(
            menukananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menukananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Grayscalebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ubahhorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ubahvertikal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(audiobawaan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(berhenti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(audioplusmp4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(putarvideo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        menutengahatas.setBackground(new java.awt.Color(52, 152, 219));
        menutengahatas.setLayout(new java.awt.CardLayout());

        isitentangkami.setBackground(new java.awt.Color(52, 152, 219));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("1. Richie");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Aplikasi Ini Dibuat Oleh :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Richie, Honggo, dan Orlen");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("3. Jonathan Orlen Pellondou");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("2. Honggo Sanjaya");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/team.png"))); // NOI18N

        isiberanda.setBackground(new java.awt.Color(52, 152, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Untuk lebih jelasnya silakan klik tombol di aplikasi ini");

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Aplikasi Ini Berisi Fitur - Fitur yang Ada di Multimedia ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/music.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/music-and-multimedia.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/cd-burning.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/computer.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/image.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectakhirmpf/watching-tv (1).png"))); // NOI18N

        javax.swing.GroupLayout isiberandaLayout = new javax.swing.GroupLayout(isiberanda);
        isiberanda.setLayout(isiberandaLayout);
        isiberandaLayout.setHorizontalGroup(
            isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiberandaLayout.createSequentialGroup()
                .addGroup(isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiberandaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isiberandaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(isiberandaLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(isiberandaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        isiberandaLayout.setVerticalGroup(
            isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiberandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiberandaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(isiberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)))
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addContainerGap(502, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout isitentangkamiLayout = new javax.swing.GroupLayout(isitentangkami);
        isitentangkami.setLayout(isitentangkamiLayout);
        isitentangkamiLayout.setHorizontalGroup(
            isitentangkamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isitentangkamiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(isitentangkamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isitentangkamiLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(isitentangkamiLayout.createSequentialGroup()
                        .addGroup(isitentangkamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        isitentangkamiLayout.setVerticalGroup(
            isitentangkamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isitentangkamiLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isitentangkamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isitentangkamiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(isitentangkamiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(isitentangkamiLayout.createSequentialGroup()
                .addComponent(isiberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menutengahatas.add(isitentangkami, "card3");

        menutengahbawah.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout menutengahbawahLayout = new javax.swing.GroupLayout(menutengahbawah);
        menutengahbawah.setLayout(menutengahbawahLayout);
        menutengahbawahLayout.setHorizontalGroup(
            menutengahbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutengahbawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(487, 487, 487))
        );
        menutengahbawahLayout.setVerticalGroup(
            menutengahbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutengahbawahLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menutengahatas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menutengahbawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menukanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menukiri, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(905, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menukanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(menutengahatas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menutengahbawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(menukiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(7, 7, 7)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 193, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int y=0;
Icon a = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\1.jpg");
Icon b = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\2.jpg");
Icon c = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\3.jpg");
Icon d = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\4.jpg");
Icon m = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\5.jpg");
Icon f = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\6.jpg");
Icon g = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\7.jpg");
Icon h = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\8.jpg");
Icon i = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\9.jpg");
Icon j = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\10.jpg");
Icon k = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\11.jpg");
Icon l = new ImageIcon("C:\\Users\\kalim\\OneDrive\\Documents\\NetBeansProjects\\freedinosprite\\12.jpg");

Timer T = new Timer(100, new ActionListener()
{
    public void actionPerformed(ActionEvent e)
    {
        y++;
        
        switch (y)
        {
            case 1:
            {
                display.setIcon(a);
                break;
            }
            case 2:
            {
                display.setIcon(b);
                break;
            }
            case 3:
            {
                display.setIcon(c);
                break;
            }
            case 4:
            {
                display.setIcon(d);
                break;
            }
            case 5:
            {
                display.setIcon(m);
                break;
            }
            case 6:
            {
                display.setIcon(f);
                break;
            }
            case 7:
            {
                display.setIcon(g);
                break;
            }
            case 8:
            {
                display.setIcon(h);
                break;
            }
            case 9:
            {
                display.setIcon(i);
                break;
            }
            case 10:
            {
                display.setIcon(j);
                break;
            }
            case 11:
            {
                display.setIcon(k);
                break;
            }
            case 12:
            {
                display.setIcon(l);
                break;
            }
        }
        
        if(y==12)
        {
            y=0;
        }
        
    }
}
);

    private void tentangkamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangkamiActionPerformed
        // TODO add your handling code here:
        menutengahatas.removeAll();
        menutengahatas.repaint();
        menutengahatas.revalidate();
        
        menutengahatas.add(isitentangkami);
        menutengahatas.repaint();
        menutengahatas.revalidate();
    }//GEN-LAST:event_tentangkamiActionPerformed

    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        // TODO add your handling code here:
        menutengahatas.removeAll();
        menutengahatas.repaint();
        menutengahatas.revalidate();
        
        menutengahatas.add(isiberanda);
        menutengahatas.repaint();
        menutengahatas.revalidate();
    }//GEN-LAST:event_berandaActionPerformed

    private void materiitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiitActionPerformed
        // TODO add your handling code here:
        materiit a = new materiit();
        a.setVisible(true);
    }//GEN-LAST:event_materiitActionPerformed

    private void kalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalkulatorActionPerformed
        // TODO add your handling code here:
        kalkulator b = new kalkulator();
        b.setVisible(true);
    }//GEN-LAST:event_kalkulatorActionPerformed

    private void animasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animasiActionPerformed
        // TODO add your handling code here:
        T.start();
    }//GEN-LAST:event_animasiActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        T.stop();
    }//GEN-LAST:event_stopActionPerformed

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        // TODO add your handling code here:
//        File jpgOriginal = new File("D:\\Pictures Drive C\\hongkong.jpg");
        File jpgOriginal = new File("D:\\Pictures Drive C\\hongkong.jpg");
        
        File jpgResized = new File("D:\\Pictures Drive C\\hongkong.jpg");
        try {
            resizeImage(jpgOriginal, jpgResized, 1000, 700, "jpg");
        } catch (IOException ex) {
            Logger.getLogger(AplikasiFinalMPF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resizeActionPerformed

    private void audiobawaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiobawaanActionPerformed
        // TODO add your handling code here:
        mp3player.play();
    }//GEN-LAST:event_audiobawaanActionPerformed

    private void ubahhorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahhorizontalActionPerformed
        // TODO add your handling code here:
        File jpgOriginal = new File("D:\\Pictures Drive C\\hongkong.jpg");
        File jpgFlipped = new File("D:\\Pictures Drive C\\fliphorizontal.jpg"); 
        flip(jpgOriginal, jpgFlipped, FLIP_HORIZONTAL);
    }//GEN-LAST:event_ubahhorizontalActionPerformed

    private void ubahvertikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahvertikalActionPerformed
        // TODO add your handling code here:
        File jpgOriginal = new File("D:\\Pictures Drive C\\hongkong.jpg");
        File jpgFlipped = new File("D:\\Pictures Drive C\\flipvertical.jpg"); 
        flip(jpgOriginal, jpgFlipped, FLIP_VERTICAL);
    }//GEN-LAST:event_ubahvertikalActionPerformed

    private void audioplusmp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioplusmp4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open(new File("PSY - New Face.mp3"));
        } catch (IOException ex) {
            Logger.getLogger(AplikasiFinalMPF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_audioplusmp4ActionPerformed

    private void putarvideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putarvideoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open(new File("Tsugi No Season - JKT48.webm"));
        } catch (IOException ex) {
            Logger.getLogger(AplikasiFinalMPF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_putarvideoActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        mp3player.pause();
    }//GEN-LAST:event_pauseActionPerformed

    private void berhentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berhentiActionPerformed
        // TODO add your handling code here:
        mp3player.stop();
    }//GEN-LAST:event_berhentiActionPerformed

    private void GrayscalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscalebtnActionPerformed
        // TODO add your handling code here:
     
        BufferedImage img = null;
        File file = null;
        file = new File("C:\\Users\\Honggo\\Documents\\NetBeansProjects\\ProjectAkhirMPF\\hongkong.jpg");
        
        try{
            img = ImageIO.read(file);
            int height = img.getHeight();
            int width = img.getWidth();
//            System.out.println("Tinggi gambar adalah "+height+" dan lebarnya adalah "+width);
            
            for(int y=0;y<height;y++)
            {
                for(int x=0;x<width;x++)
                {
                    int p = img.getRGB(x, y);
                    int a = (p>>54)&0xff;
                    int r = (p>>26)&0xff;
                    int g = (p>>28)&0xff;
                    int b = (p)&0xff;
                    
                    int avg = (r+g+b)/3;
                    
                    p = (a<<54)|(avg<<26)|(avg<<28)|(avg);
                    img.setRGB(x, y, p);
                }
            }
            
            file = new File("C:\\Users\\Honggo\\Documents\\NetBeansProjects\\ProjectAkhirMPF\\gray.jpg");
            ImageIO.write(img, "png", file);
            
        } catch(IOException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_GrayscalebtnActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed
    
    private static void resizeImage(File originalImage, File resizedImage, int width, int height, String format) throws IOException{
        try{
        BufferedImage original = ImageIO.read(originalImage);
        BufferedImage resized = new BufferedImage(width, height, original.getType());
        Graphics2D g2 = resized.createGraphics();
        g2.drawImage(original, 0, 0, width, height, null);
        g2.dispose();
        ImageIO.write(resized, format, resizedImage);
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }
    
    public static final int FLIP_VERTICAL = 1;
    public static final int FLIP_HORIZONTAL = -1;
    
    private static void flip(File Input, File Output, int direction){
        try {
            BufferedImage image = ImageIO.read(Input);
            int width = image.getWidth();
            int height = image.getHeight();
            BufferedImage flipped = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            
            for(int y=0; y<height; y++)
            {
                for(int x=0; x<width;x++)
                {
                    switch(direction){
                        case FLIP_HORIZONTAL:
                            flipped.setRGB((width-1)-x, y, image.getRGB(x, y));
                            break;
                        case FLIP_VERTICAL:
                            flipped.setRGB(x, (height-1)-y, image.getRGB(x, y));
                            break;
                    }
                }
            }
            ImageIO.write(flipped, "jpg", Output);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiFinalMPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiFinalMPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiFinalMPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiFinalMPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiFinalMPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Grayscalebtn;
    private javax.swing.JButton animasi;
    private javax.swing.JButton audiobawaan;
    private javax.swing.JButton audioplusmp4;
    private javax.swing.JPanel background;
    private javax.swing.JButton beranda;
    private javax.swing.JButton berhenti;
    private javax.swing.JLabel display;
    private javax.swing.JPanel isiberanda;
    private javax.swing.JPanel isitentangkami;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kalkulator;
    private javax.swing.JButton materiit;
    private javax.swing.JPanel menukanan;
    private javax.swing.JPanel menukiri;
    private javax.swing.JPanel menutengahatas;
    private javax.swing.JPanel menutengahbawah;
    private javax.swing.JButton pause;
    private javax.swing.JButton putarvideo;
    private javax.swing.JButton resize;
    private javax.swing.JButton stop;
    private javax.swing.JButton tentangkami;
    private javax.swing.JButton ubahhorizontal;
    private javax.swing.JButton ubahvertikal;
    // End of variables declaration//GEN-END:variables
}
